var MENU00 = "HOME";
var MENU10 = "NOTÍCIAS";
var MENU11 = "ANÚNCIO";
var MENU12 = "EVENTOS";
var MENU20 = "JOGO GUIAS";
var MENU21 = "GUIAS DE BASE";
var MENU22 = "INFO";
var MENU23 = "SISTEMA DE JOGO";
var MENU24 = "PERSONAGENS";
var MENU25 = "GUIAS EM FILMES";

//var MENU210 = "GUIAS DE INICIANTES";
//var MENU211 = "GUIAS DE INICIANTES";
var MENU210 = "GUIAS DE BASE";
var MENU211 = "SUN TOTAL GUIDE";
var MENU212 = "INSTALAÇÃO";
var MENU213 = "INTERFACE";
var MENU214 = "CONTROLES";
var MENU215 = "CRIAR PERSONAGEM & WAYPOINT";
var MENU216 = "GUIA DO CASH SHOP";
var MENU217 = "SPECIAL PACKAGE GUIDE";

//
var MENU220 = "INFO";
var MENU221 = "CARACTERÍSTICAS DO JOGO";
var MENU222 = "CENÁRIO";

//
var MENU230 = "SISTEMA DE JOGO";
var MENU231 = "BATTLE ZONE";
var MENU232 = "SKILL / STYLE";
var MENU233 = "AQUISIÇÃO DE COMPETÊNCIAS";
var MENU234 = "CONQUISTA ESPAÇO";
var MENU235 = "PARTIDO";
var MENU236 = "GUILD";
var MENU237 = "MOUNTS";
var MENU238 = "MULTI-LANGUAGE SERVICE";
var MENU239 = "CURSED TOWERS";
var MENU239_1 = "LUCKY HEIM SYSTEM";
var MENU239_2 = "ONLINE POINTS SYSTEM";
var MENU239_3 = "GROUP SYSTEM";
var MENU239_4 = "TERRITORIAL TAKEOVER SYSTEM";

//
var MENU240 = "PERSONAGENS";
var MENU241 = "BERSERKER";
var MENU242 = "VALKYRIE";
var MENU243 = "CAVALEIRO DE DRAGÃO";
var MENU244 = "ELEMENTALIST";
var MENU245 = "SOMBRA";

//GUIDE MOVIES
var MENU250 = "GUIAS EM FILMES";
var MENU251 = "FOREST OF BEASTS";
var MENU252 = "ETHERAIN SEWER";
var MENU253 = "FROZEN PALACE";
var MENU254 = "VALLEY  OF THE DRAGONKIN";
var MENU255 = "AIORT GRAVEYARD";
var MENU256 = "HELRON'S CASTLE";
var MENU257 = "ETC";

var MENU30 = "COMUNIDADE";
var MENU31 = "VIDEO FORUM";
var MENU32 = "S.U.N FORUM";
var MENU33 = "FANSITE S.U.N";
var MENU40 = "MEDIA";
var MENU41 = "SCREENSHOTS";
var MENU42 = "PAPEIS DE PAREDE";
var MENU43 = "CONCEITO DE ARTES";

var MENU50 = "LOJA";
var MENU51 = "LOJA DE ITEM S.U.N ";
var MENU52 = "PACOTE DE SERVIÇO ESPECIAL";
var MENU53 = "GUIA DE COMPRAS";
var MENU54 = "COMPRAR W COIN";

var MENU60 = "RANKING";
var MENU61 = "AC RANKING";
var MENU610 = "AC RANKING";
var MENU611 = "AC HALL OF FAME";
var MENU612 = "DAILY TOP 100";
var MENU62 = "NÍVEL DE CLASSIFICAÇÃO";
var MENU620 = "NÍVEL DE CLASSIFICAÇÃO";
var MENU63 = "RANKING DE GUILD";
var MENU630 = "RANKING DE GUILD";
var MENU70 = "INFORMAÇÕES";
var MENU71 = "SOBRE A EMPRESA";
var MENU72 = "POLÍTICA DE PRIVACIDADE";
var MENU73 = "TERMOS DO SERVIÇO";
var MENU74 = "CONTATO E.U.";
var MENU75 = "STARTER PLUG-IN";
var MENU80 = "DOWNLOAD";
var MENU81 = "DOWNLOAD";