<?php            
$PageRequest = strtolower(basename( $_SERVER['REQUEST_URI'] ));
$PageName = strtolower(basename( __FILE__ ));
if($PageRequest == $PageName) exit("<strong> Erro: N&atilde;o &eacute; permitido acessar o arquivo diretamente. </strong>");
 
class ldItemOptionsDatabase 
{
    public function __construct() { } 
        
    /**
    * @desc get socket options name.
    */
    public static function getSocket()
    {
        global $VIRTUAL_VAULT;
        if(isset($VIRTUAL_VAULT['MUSERVER_MANUFACTURER']) == false)
            $manufacturer = 0;
        $options = array(
            "notSocket" => ($manufacturer == 0 ? 255 : 0) ,
            "emptySocket" => ($manufacturer == 0 ? 254 : 255),
            "socketTypeNumber" => array(
                                            ($manufacturer == 0 ? 255 : 0) => array("socketTypeName" => "No socket", 
                                                       "socketName" => "No Socket", 
                                                       "socketsArgs" => array(1 => "0", 2 => "0", 3 => "0", 4 => "0", 5 => "0")
                                                       ),
                                            ($manufacturer == 0 ? 254 : 255) => array("socketTypeName" => "Empty socket", 
                                                       "socketName" => "Empty Socket", 
                                                       "socketsArgs" => array(1 => "0", 2 => "0", 3 => "0", 4 => "0", 5 => "0")
                                                       ),
                                            0 => array("socketTypeName" => "Fire", 
                                                       "socketName" => "Increase Damage", 
                                                       "socketsArgs" => array(1 => "20", 2 => "400", 3 => "400", 4 => "400", 5 => "400")
                                                       ),
                                            1 => array("socketTypeName" => "Fire", 
                                                       "socketName" => "Increase Attack Speed", 
                                                       "socketsArgs" => array(1 => "7", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                            2 => array("socketTypeName" => "Fire", 
                                                       "socketName" => "Increase Max Damage/Skill Power", 
                                                       "socketsArgs" => array(1 => "30", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                            3 => array("socketTypeName" => "Fire", 
                                                       "socketName" => "Increase Min Damage/Skill Power", 
                                                       "socketsArgs" => array(1 => "20", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                            4 => array("socketTypeName" => "Fire", 
                                                       "socketName" => "Increase Damage/Skill Power", 
                                                       "socketsArgs" => array(1 => "20", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ), 
                                            5 => array("socketTypeName" => "Fire", 
                                                       "socketName" => "Decrease AG consumption", 
                                                       "socketsArgs" => array(1 => "40", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ), 
                                                       
                                           10 => array("socketTypeName" => "Water", 
                                                       "socketName" => "Increase Defense Success Rate", 
                                                       "socketsArgs" => array(1 => "10", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                           11 => array("socketTypeName" => "Water", 
                                                       "socketName" => "Increase Defense", 
                                                       "socketsArgs" => array(1 => "30", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                           12 => array("socketTypeName" => "Water", 
                                                       "socketName" => "Increase Shield Defense", 
                                                       "socketsArgs" => array(1 => "7", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                           13 => array("socketTypeName" => "Water", 
                                                       "socketName" => "Increase Damage Reduction", 
                                                       "socketsArgs" => array(1 => "4", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                           14 => array("socketTypeName" => "Water", 
                                                       "socketName" => "Increase Damage Reflect", 
                                                       "socketsArgs" => array(1 => "5", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ), 
                                                       
                                           16 => array("socketTypeName" => "Ice", 
                                                       "socketName" => "Increase Recover Life", 
                                                       "socketsArgs" => array(1 => "8", 2 => "49", 3 => "50", 4 => "51", 5 => "52")
                                                       ),
                                           17 => array("socketTypeName" => "Ice", 
                                                       "socketName" => "Increase Recover Mana",                                  
                                                       "socketsArgs" => array(1 => "8", 2 => "49", 3 => "50", 4 => "51", 5 => "52")
                                                       ),
                                           18 => array("socketTypeName" => "Ice", 
                                                       "socketName" => "Increase Skill Damage", 
                                                       "socketsArgs" => array(1 => "37", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                           19 => array("socketTypeName" => "Ice", 
                                                       "socketName" => "Increase Attack Success Rate", 
                                                       "socketsArgs" => array(1 => "25", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                           20 => array("socketTypeName" => "Ice", 
                                                       "socketName" => "Increase Item Durability", 
                                                       "socketsArgs" => array(1 => "30", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                                       
                                           21 => array("socketTypeName" => "Wind", 
                                                       "socketName" => "Increase Life Autorecovery", 
                                                       "socketsArgs" => array(1 => "8", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                           22 => array("socketTypeName" => "Wind", 
                                                       "socketName" => "Increase Max HP",                                  
                                                       "socketsArgs" => array(1 => "4", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                           23 => array("socketTypeName" => "Wind", 
                                                       "socketName" => "Increase Max MP", 
                                                       "socketsArgs" => array(1 => "4", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                           24 => array("socketTypeName" => "Wind", 
                                                       "socketName" => "Increase Mana Autorecovery", 
                                                       "socketsArgs" => array(1 => "7", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                           25 => array("socketTypeName" => "Wind", 
                                                       "socketName" => "Increase Max AG", 
                                                       "socketsArgs" => array(1 => "25", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                           26 => array("socketTypeName" => "Wind", 
                                                       "socketName" => "Increase AG Autorecovery", 
                                                       "socketsArgs" => array(1 => "3", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ), 
                                                       
                                           29 => array("socketTypeName" => "Lightning", 
                                                       "socketName" => "Increase Excellent Damage", 
                                                       "socketsArgs" => array(1 => "15", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                           30 => array("socketTypeName" => "Lightning", 
                                                       "socketName" => "Increase Excellent Damage Rate",                                  
                                                       "socketsArgs" => array(1 => "10", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                           31 => array("socketTypeName" => "Lightning", 
                                                       "socketName" => "Increase Critical Damage", 
                                                       "socketsArgs" => array(1 => "30", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ),
                                           32 => array("socketTypeName" => "Lightning", 
                                                       "socketName" => "Increase Critical Damage Rate", 
                                                       "socketsArgs" => array(1 => "8", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ), 
                                                       
                                           36 => array("socketTypeName" => "Ground", 
                                                       "socketName" => "Increase Strength", 
                                                       "socketsArgs" => array(1 => "30", 2 => "1", 3 => "1", 4 => "1", 5 => "1")
                                                       ), 
                                        ) 
        );
        return $options;
    }
    
    /**
    * @desc get harmony options name.
    */
    public static function getHarmony($family, $type, $level)
    {
        if($family >= 0 && $family <= 4) $family = 1;
        elseif($family == 5) $family = 2;
        elseif($family >= 6 || $family <= 11) $family = 3;
        else $family = 0;
        
        switch($family)
        {    // 0 : Não tem , 1 : Weapons, 2 : Staffs, 3 : Sets/Shields
            case 0:
                $options = array(
                        0 => array("name" => "No option 0", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        1 => array("name" => "No option 1", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        2 => array("name" => "No option 2", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        3 => array("name" => "No option 3", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        4 => array("name" => "No option 4", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        5 => array("name" => "No option 5", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        6 => array("name" => "No option 6", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        7 => array("name" => "No option 7", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        8 => array("name" => "No option 8", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        9 => array("name" => "No option 9", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        10 => array("name" => "No option 10", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        11 => array("name" => "No option 11", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        12 => array("name" => "No option 12", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        13 => array("name" => "No option 13", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        14 => array("name" => "No option 14", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        15 => array("name" => "No option 15", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                ); 
                break;
            case 1:
                $options = array(
                        0 => array("name" => "No option 0", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        1 => array("name" => "Min Attack Power +", 
                                   0 => 2,
                                   1 => 3,
                                   2 => 4,
                                   3 => 5,
                                   4 => 6,
                                   5 => 7,
                                   6 => 9,
                                   7 => 11,
                                   8 => 12,
                                   9 => 14,
                                   10 => 15,
                                   11 => 16,
                                   12 => 17,
                                   13 => 20,
                                   14 => 100000,
                                   15 => 110000,
                        ),
                        2 => array("name" => "Max Attack Power +", 
                                   0 => 3,
                                   1 => 4,
                                   2 => 5,
                                   3 => 6,
                                   4 => 7,
                                   5 => 8,
                                   6 => 10,
                                   7 => 12,
                                   8 => 14,
                                   9 => 17,
                                   10 => 20,
                                   11 => 23,
                                   12 => 26,
                                   13 => 29,
                                   14 => 100000,
                                   15 => 110000,
                        ),
                        3 => array("name" => "Need Strength -", 
                                   0 => 6,
                                   1 => 8,
                                   2 => 10,
                                   3 => 12,
                                   4 => 14,
                                   5 => 16,
                                   6 => 20,
                                   7 => 23,
                                   8 => 26,
                                   9 => 29,
                                   10 => 32,
                                   11 => 35,
                                   12 => 37,
                                   13 => 40,
                                   14 => 100000,
                                   15 => 110000,
                        ),
                        4 => array("name" => "Need Agility -", 
                                   0 => 6,
                                   1 => 8,
                                   2 => 10,
                                   3 => 12,
                                   4 => 14,
                                   5 => 16,
                                   6 => 20,
                                   7 => 23,
                                   8 => 26,
                                   9 => 29,
                                   10 => 32,
                                   11 => 35,
                                   12 => 37,
                                   13 => 40,
                                   14 => 100000,
                                   15 => 110000,
                        ),
                        5 => array("name" => "Attack (Max, Min) +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 7,
                                   7 => 8,
                                   8 => 9,
                                   9 => 11,
                                   10 => 12,
                                   11 => 14,
                                   12 => 16,
                                   13 => 19,
                                   14 => 0,
                                   15 => 0,
                        ),
                        6 => array("name" => "Critical Damage +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 12,
                                   7 => 14,
                                   8 => 16,
                                   9 => 18,
                                   10 => 20,
                                   11 => 22,
                                   12 => 24,
                                   13 => 30,
                                   14 => 0,
                                   15 => 0, 
                        ),
                        7 => array("name" => "Skill Power +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 12,
                                   10 => 14,
                                   11 => 16,
                                   12 => 18,
                                   13 => 22,
                                   14 => 0,
                                   15 => 0,
                        ),
                        8 => array("name" => "Attack % Rate +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 5,
                                   10 => 7,
                                   11 => 9,
                                   12 => 11,
                                   13 => 14,
                                   14 => 0,
                                   15 => 0,
                        ),
                        9 => array("name" => "SD - Rate +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 3,
                                   10 => 5,
                                   11 => 7,
                                   12 => 9,
                                   13 => 10,
                                   14 => 0,
                                   15 => 0,
                        ),
                        10 => array("name" => "SD Ignore Rate +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 10,
                                   14 => 0,
                                   15 => 0,
                        ),
                        11 => array("name" => "No option 11", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        12 => array("name" => "No option 12", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        13 => array("name" => "No option 13", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        14 => array("name" => "No option 14", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        15 => array("name" => "No option 15", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                ); 
                break;
            case 2:
                $options = array(
                        0 => array("name" => "No option 0", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        1 => array("name" => "Magic Power +", 
                                   0 => 6,
                                   1 => 8,
                                   2 => 10,
                                   3 => 12,
                                   4 => 14,
                                   5 => 16,
                                   6 => 17,
                                   7 => 18,
                                   8 => 19,
                                   9 => 21,
                                   10 => 23,
                                   11 => 25,
                                   12 => 27,
                                   13 => 31,
                                   14 => 100000,
                                   15 => 110000,
                        ),
                        2 => array("name" => "Need Strength -", 
                                   0 => 6,
                                   1 => 8,
                                   2 => 10,
                                   3 => 12,
                                   4 => 14,
                                   5 => 16,
                                   6 => 20,
                                   7 => 23,
                                   8 => 26,
                                   9 => 29,
                                   10 => 32,
                                   11 => 35,
                                   12 => 37,
                                   13 => 40,
                                   14 => 100000,
                                   15 => 110000,
                        ),
                        3 => array("name" => "Need Agility -", 
                                   0 => 6,
                                   1 => 8,
                                   2 => 10,
                                   3 => 12,
                                   4 => 14,
                                   5 => 16,
                                   6 => 20,
                                   7 => 23,
                                   8 => 26,
                                   9 => 29,
                                   10 => 32,
                                   11 => 35,
                                   12 => 37,
                                   13 => 40,
                                   14 => 100000,
                                   15 => 110000,
                        ),
                        4 => array("name" => "Skill Power +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 7,
                                   7 => 10,
                                   8 => 13,
                                   9 => 16,
                                   10 => 19,
                                   11 => 22,
                                   12 => 25,
                                   13 => 30,
                                   14 => 0,
                                   15 => 0,
                        ),
                        5 => array("name" => "Critical Damage +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 10,
                                   7 => 12,
                                   8 => 14,
                                   9 => 16,
                                   10 => 18,
                                   11 => 20,
                                   12 => 22,
                                   13 => 28,
                                   14 => 0,
                                   15 => 0,
                        ),
                        6 => array("name" => "SD - Rate +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 4,
                                   10 => 6,
                                   11 => 8,
                                   12 => 10,
                                   13 => 13,
                                   14 => 0,
                                   15 => 0,
                        ),
                        7 => array("name" => "Attack % Rate +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        8 => array("name" => "SD Ignore Rate +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        9 => array("name" => "No option 9", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        10 => array("name" => "No option 10", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        11 => array("name" => "No option 11", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        12 => array("name" => "No option 12", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        13 => array("name" => "No option 13", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        14 => array("name" => "No option 14", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        15 => array("name" => "No option 15", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                ); 
                break;
            case 3:
                $options = array(
                        0 => array("name" => "No option 0", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        1 => array("name" => "Def Power +", 
                                   0 => 3,
                                   1 => 4,
                                   2 => 5,
                                   3 => 6,
                                   4 => 7,
                                   5 => 8,
                                   6 => 10,
                                   7 => 12,
                                   8 => 14,
                                   9 => 16,
                                   10 => 18,
                                   11 => 20,
                                   12 => 22,
                                   13 => 25,
                                   14 => 100000,
                                   15 => 110000,
                        ),
                        2 => array("name" => "Max AG +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 4,
                                   4 => 6,
                                   5 => 8,
                                   6 => 10,
                                   7 => 12,
                                   8 => 14,
                                   9 => 16,
                                   10 => 18,
                                   11 => 20,
                                   12 => 22,
                                   13 => 25,
                                   14 => 0,
                                   15 => 0,
                        ),
                        3 => array("name" => "Max HP +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 7,
                                   4 => 9,
                                   5 => 11,
                                   6 => 13,
                                   7 => 15,
                                   8 => 17,
                                   9 => 19,
                                   10 => 21,
                                   11 => 23,
                                   12 => 25,
                                   13 => 30,
                                   14 => 0,
                                   15 => 0,
                        ),
                        4 => array("name" => "HP Auto Rate +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 1,
                                   7 => 2,
                                   8 => 3,
                                   9 => 4,
                                   10 => 5,
                                   11 => 6,
                                   12 => 7,
                                   13 => 8,
                                   14 => 0,
                                   15 => 0,
                        ),
                        5 => array("name" => "MP Auto Rate +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 1,
                                   10 => 2,
                                   11 => 3,
                                   12 => 7,
                                   13 => 8,
                                   14 => 0,
                                   15 => 0,
                        ),
                        6 => array("name" => "Def Success Rate +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 3,
                                   10 => 4,
                                   11 => 5,
                                   12 => 6,
                                   13 => 8,
                                   14 => 0,
                                   15 => 0,
                        ),
                        7 => array("name" => "Dmg - Rate +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 3,
                                   10 => 4,
                                   11 => 5,
                                   12 => 6,
                                   13 => 7,
                                   14 => 0,
                                   15 => 0,
                        ),
                        8 => array("name" => "SD Rate +", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 5,
                                   14 => 0,
                                   15 => 0,
                        ),
                        9 => array("name" => "No option 9", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        10 => array("name" => "No option 10", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        11 => array("name" => "No option 11", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        12 => array("name" => "No option 12", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        13 => array("name" => "No option 13", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        14 => array("name" => "No option 14", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                        15 => array("name" => "No option 15", 
                                   0 => 0,
                                   1 => 0,
                                   2 => 0,
                                   3 => 0,
                                   4 => 0,
                                   5 => 0,
                                   6 => 0,
                                   7 => 0,
                                   8 => 0,
                                   9 => 0,
                                   10 => 0,
                                   11 => 0,
                                   12 => 0,
                                   13 => 0,
                                   14 => 0,
                                   15 => 0,
                        ),
                ); 
                break;
        }
        return $options[$type]["name"].$options[$type][$level];
    }
            
    /**
    * @desc get refine options name.
    */
    public static function getRefine($family, $index)
    {
        if($family >= 0 && $family <= 6) $type = 6;
        elseif($family == 7) $type = 1;
        elseif($family == 8) $type = 2;
        elseif($family == 9) $type = 3;
        elseif($family == 10) $type = 4;
        elseif($family == 11) $type = 5;
        else 
            $type = 0;    
        
        switch($type)
        {
            case 0: 
                return (object) array(
                        "name" => "No option",
                        "opt0" => "No Refinery 1º Options",
                        "opt1" => "No Refinery 2º Options",
                ); 
                break;
            case 1: 
                return (object) array(
                        "name" => "Helms",
                        "opt0" => "SD Recovery Rate +20",
                        "opt1" => "Defense Success Rate +10",
                ); 
                break;
            case 2: 
                return (object) array(
                        "name" => "Armors",
                        "opt0" => "SD Auto Recovery",
                        "opt1" => "Def Success Rate +10",
                ); 
                break;
            case 3: 
                return (object) array(
                        "name" => "Pants",
                        "opt0" => "Def Skill +200",
                        "opt1" => "Def Success Rate +10",
                ); 
                break;
            case 4: 
                return (object) array(
                        "name" => "Gloves",
                        "opt0" => "Max HP +200",
                        "opt1" => "Def Success Rate +10",
                ); 
                break;
            case 5: 
                return (object) array(
                        "name" => "Boots",
                        "opt0" => "Max SD +700",
                        "opt1" => "Def Success Rate +10",
                ); 
                break;
            case 6: 
                return (object) array(
                        "name" => "Weapons",
                        "opt0" => "Additional Dmg +200",
                        "opt1" => "Pow Success Rate +10",
                ); 
                break;
        }
    }
    
    /**
    * @desc get excellents options name.
    */
    public static function getExcellents($family, $index)
    {
        if($family == 0 || $family == 1 || $family == 2 || $family == 3 || $family == 4 || $family == 5) 
            $type = 1;     
        elseif($family == 6 || $family == 7 || $family == 8 || $family == 9 || $family == 10 || $family == 11) 
            $type = 2;    
        elseif($family == 12)
        {
            if($index >= 3 && $index <= 6) $type = 3; //Asas level 2
            if($index >= 36 && $index <= 43) $type = 7; //Asas level 3
            if($index >= 130 && $index <= 134) $type = 3; //Small Asas
        }     
        elseif($family == 13)
        {
            if($index >= 8 && $index <= 9) $type = 5; //Rings
            if($index >= 12 && $index <= 13) $type = 6; //Pendants
            if($index >= 20 && $index <= 24) $type = 5; //Rings
            if($index >= 25 && $index <= 28) $type = 6; //Pendants
            if($index >= 33) $type = 3; //Capa Dark Lord
            if($index >= 37) $type = 4; //Fenrir
        }
        else 
            $type = 0;    
        
        switch($type)
        {
            case 0: 
                return (object) array(
                        "name" => "No effect",
                        "opt0" => "No effect",
                        "opt1" => "No effect",
                        "opt2" => "No effect",
                        "opt3" => "No effect",
                        "opt4" => "No effect",
                        "opt5" => "No effect",
                );
                break;
            case 1: 
                return (object) array(
                        "name" => "EXE WEAPONS",
                        "opt0" => "Increases recovery rate of mana (Mana / 8)",
                        "opt1" => "Increases recovery rate of life (Life / 8)",
                        "opt2" => "Increase the speed of magical damage +7",
                        "opt3" => "Increase magical damage +1%",
                        "opt4" => "Increase magic damage + level/20",
                        "opt5" => "Success in excellent damage +10%",
                );
            case 2: 
                return (object) array(
                        "name" => "EXE SETS",
                        "opt0" => "Increased rate of acquisition of Zen +40%",
                        "opt1" => "Success of Defense +10%",
                        "opt2" => "Mirrors in 5% Damage Received",
                        "opt3" => "Lowers the damage by +4%",
                        "opt4" => "Increase mana +4%",
                        "opt5" => "Increases in life +4%",
                );
                break;
            case 3: 
                return (object) array(
                        "name" => "EXE WINGS",
                        "opt0" => "Life increased by +125",
                        "opt1" => "Mana increased by +125",
                        "opt2" => "Defense of the opponent ignored by 3%",
                        "opt3" => "Stamina increased by +50",
                        "opt4" => "Increase the speed of magic damage to +5",
                        "opt5" => "No effect",
                );
            case 4: 
                return (object) array(
                        "name" => "EXE FENRIR",
                        "opt0" => "+Damage",
                        "opt1" => "+Defense",
                        "opt2" => "+Illusion",
                        "opt3" => "No effect",
                        "opt4" => "No effect",
                        "opt5" => "No effect",
                );
                break;
            case 5: 
                return (object) array(
                        "name" => "RINGS",
                        "opt0" => "Increases zens who fall into +40%",
                        "opt1" => "+10% Defensive success rank",
                        "opt2" => "Returns the blow +5%",
                        "opt3" => "Received low blow +4%",
                        "opt4" => "Increase mana +4%",
                        "opt5" => "Increases in life +4%",
                );
            case 6: 
                return (object) array(
                        "name" => "PENDANTS",
                        "opt0" => "Increase mana after killing monster + mana / 8",
                        "opt1" => "Increases life after killing monster + life / 8",
                        "opt2" => "Increases attack speed +7",
                        "opt3" => "Adds +2% damage",
                        "opt4" => "+ Increases damage level/20",
                        "opt5" => "+10% Defensive success rank",
                );
            case 7: 
                return (object) array(
                        "name" => "EXE WINGS S4",
                        "opt0" => "Ignore the Power of Defensive Opponent 5%",
                        "opt1" => "5% Chance to return the damage",
                        "opt2" => "5% Chance of a lifetime to recover",
                        "opt3" => "5% Chance to recover all mana",
                        "opt4" => "No effect",
                        "opt5" => "No effect",
                );
                break; 
        }
    }
}
?>